/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arr_AddNumber;

import java.util.Scanner;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
public class App {

    public static void main(String[] args) {
        System.out.println("Nhap kich thuoc mang: ");
        int n = new Scanner(System.in).nextInt();
        List<Integer> arrayList = new ArrayList<>();
        for (int i = 0 ; i < n;i++) {
            arrayList.add((int)(Math.random() * 100));
        }
        System.out.println("Mang vua tao:");
        for(int Number: arrayList){
            System.out.print(Number + " ");
        }
        System.out.println("");
        System.out.println("Nhap so muon them: ");
        int x = new Scanner(System.in).nextInt();

        arrayList.add(x);
        
        Collections.sort(arrayList);
        
        System.out.println("Mang sau khi them va sap xep:");
        for(int Number: arrayList){
            System.out.print(Number + " ");
        }
    }
}
