/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package two.wayArray;

import org.junit.jupiter.api.Test;


class AppTest {
    @Test void appHasAGreeting() {
        
    }
}
