/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UCLN;

import java.util.Scanner;

public class App {
    public static int UCLN(int a, int b){
        while(a * b != 0){
            if(a > b){
                a %= b;
            }
            else{
                b %= a;
            }
        }
        return a + b; // Khi do a or b = 0;
    }

    public static void main(String[] args) {
        Scanner inputScanner = new Scanner(System.in);
        
        System.out.println("Nhap so thu nhat: ");
        int a = inputScanner.nextInt();
        System.out.println("Nhap so thu hai: ");
        int b = inputScanner.nextInt();
        
        System.out.printf("UCLN cua 2 so %d va %d la %d",a,b,UCLN(a,b));
    }
}
