/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Test_netbean;

import java.util.*;

public class App {
    public static void main(String[] args) {
        Scanner inpuScanner = new Scanner(System.in);
        
        int a = inpuScanner.nextInt();
        int b = inpuScanner.nextInt();
        
        System.out.println("Tong hai so: " + (a+b));
        inpuScanner.close();
    }
}
