/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package two.wayArray;

import java.util.Arrays;

public class App {
    public static void multiplyArr(int[][] arr1, int[][] arr2) {
        if(arr1.length == arr2[0].length){
            int[][] result = new int[arr1.length][arr2[0].length];
            for(int i = 0 ; i < arr1.length;i++){
                for(int j = 0 ;j < arr2[0].length;j++){
                    result[i][j] = 0;
                    for(int k = 0 ; k < arr2.length;k++){
                        result[i][j] += (arr1[i][k]*arr2[k][j]);
                    }
                }
            }
            System.out.println("Tich hai ma tran la: " + Arrays.deepToString(result));
        }
        else{
            System.out.println("Khong the nhan do khong cung kich co hang, cot");
        }
    }

    public static void main(String[] args) {
        int[][] arr1 = new int[3][4]; // cot hang
        int[][] arr2 = new int[2][3]; // cot hang
        
        for(int i = 0;i < arr1.length;i++){
            for(int j = 0 ; j < arr1[0].length;j++){
                arr1[i][j] = (int)(Math.random()*100);
            }
        }
        for(int i = 0;i < arr2.length;i++){
            for(int j = 0 ; j < arr2[0].length;j++){
                arr2[i][j] = (int)(Math.random()*100);
            }
        }
        System.out.println("Ma tran thu nhat: " + Arrays.deepToString(arr1));
        System.out.println("Ma tran thu hai: " + Arrays.deepToString(arr2));
        
        multiplyArr(arr1, arr2);
    }
}
