/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tinh_Giai_Thua;

import java.util.Scanner;

public class App {
    public static int GiaiThua(int n){
        int sum = 1;
        for(int i = 1; i <= n; i++){
            sum *= i;
        }
        return sum;
    }

    public static void main(String[] args) {
        System.out.println("Nhap so can tinh: ");
        int n = new Scanner(System.in).nextInt();
        System.out.println(n + " giai thua la: " + GiaiThua(n));
    }
}
